/**
 * @class     MainForm
 * @version   0.01
 * @date      8 November 2010
 * @author    Sergey Khechumov, Jalal Noureddine (Team B)
 */

package IPR;

import java.awt.Toolkit; // To add the icon on the form
import javax.swing.JOptionPane; // To use JOptionPane message box

public class MainForm extends javax.swing.JFrame {

    /** Creates new form MainForm */
    public MainForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRun = new javax.swing.JButton();
        txtRadicand = new javax.swing.JTextField();
        btnHelpRadicand = new javax.swing.JButton();
        txtDegree = new javax.swing.JTextField();
        txtAccuracy = new javax.swing.JTextField();
        btnHelpDegree = new javax.swing.JButton();
        btnHelpAccuracy = new javax.swing.JButton();
        lblRadicand = new javax.swing.JLabel();
        lblDegree = new javax.swing.JLabel();
        lblAccuracy = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();
        jMainMenu = new javax.swing.JMenuBar();
        jProgram = new javax.swing.JMenu();
        jRun = new javax.swing.JMenuItem();
        jClose = new javax.swing.JMenuItem();
        jSave = new javax.swing.JMenu();
        jSaveXML = new javax.swing.JMenuItem();
        jSaveTxt = new javax.swing.JMenuItem();
        jHelp = new javax.swing.JMenu();
        jShowHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Incredible Prime Root");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Andalus", 0, 14));
        setIconImage(Toolkit.getDefaultToolkit().getImage(MainForm.class.getResource("TeamB.gif")));
        setResizable(false);

        btnRun.setFont(new java.awt.Font("Tahoma", 1, 14));
        btnRun.setForeground(new java.awt.Color(153, 0, 153));
        btnRun.setText("RUN");
        btnRun.setToolTipText("Compute this root.");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });

        txtRadicand.setFont(new java.awt.Font("Tahoma", 0, 12));
        txtRadicand.setToolTipText("Enter a radicant here. To know more, press the \"?\" button on the right.");
        txtRadicand.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRadicandFocusLost(evt);
            }
        });

        btnHelpRadicand.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnHelpRadicand.setForeground(new java.awt.Color(0, 51, 204));
        btnHelpRadicand.setText("?");
        btnHelpRadicand.setToolTipText("What is radicand?");
        btnHelpRadicand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpRadicandActionPerformed(evt);
            }
        });

        txtDegree.setFont(new java.awt.Font("Tahoma", 0, 12));
        txtDegree.setToolTipText("Enter a degree here. To know more, press the \"?\" button on the right.");
        txtDegree.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDegreeFocusLost(evt);
            }
        });

        txtAccuracy.setFont(new java.awt.Font("Tahoma", 0, 12));
        txtAccuracy.setToolTipText("Enter an accuracy here. To know more, press the \"?\" button on the right.");
        txtAccuracy.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAccuracyFocusLost(evt);
            }
        });

        btnHelpDegree.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnHelpDegree.setForeground(new java.awt.Color(0, 51, 204));
        btnHelpDegree.setText("?");
        btnHelpDegree.setToolTipText("What is degree?");
        btnHelpDegree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpDegreeActionPerformed(evt);
            }
        });

        btnHelpAccuracy.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnHelpAccuracy.setForeground(new java.awt.Color(0, 51, 204));
        btnHelpAccuracy.setText("?");
        btnHelpAccuracy.setToolTipText("What is accuracy?");
        btnHelpAccuracy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpAccuracyActionPerformed(evt);
            }
        });

        lblRadicand.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblRadicand.setText("Radicand");

        lblDegree.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblDegree.setText("Degree");

        lblAccuracy.setFont(new java.awt.Font("Tahoma", 1, 12));
        lblAccuracy.setText("Accuracy");

        txtResult.setColumns(20);
        txtResult.setEditable(false);
        txtResult.setFont(new java.awt.Font("Meiryo UI", 1, 14));
        txtResult.setRows(1);
        txtResult.setToolTipText("The result will appear here after you select the RUN button.");
        txtResult.setFocusable(false);
        txtResult.setName("txtResult"); // NOI18N
        txtResult.setOpaque(false);
        jScrollPane1.setViewportView(txtResult);

        jProgram.setToolTipText("Run or close this application.");
        jProgram.setLabel("Program");

        jRun.setText("Run");
        jRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRunActionPerformed(evt);
            }
        });
        jProgram.add(jRun);

        jClose.setText("Close");
        jClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCloseActionPerformed(evt);
            }
        });
        jProgram.add(jClose);

        jMainMenu.add(jProgram);

        jSave.setText("Save");
        jSave.setToolTipText("Save your results.");

        jSaveXML.setText("Save as XML...");
        jSaveXML.setActionCommand("SaveXML");
        jSaveXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveXMLActionPerformed(evt);
            }
        });
        jSave.add(jSaveXML);

        jSaveTxt.setText("Save as TXT...");
        jSaveTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveTxtActionPerformed(evt);
            }
        });
        jSave.add(jSaveTxt);

        jMainMenu.add(jSave);

        jHelp.setText("Help ");
        jHelp.setToolTipText("Help topics for this application.");

        jShowHelp.setText("Help topics");
        jShowHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowHelpActionPerformed(evt);
            }
        });
        jHelp.add(jShowHelp);

        jMainMenu.add(jHelp);

        setJMenuBar(jMainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addComponent(btnRun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAccuracy, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDegree, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRadicand, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAccuracy, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHelpAccuracy))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDegree, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHelpDegree))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRadicand, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHelpRadicand)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRadicand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHelpRadicand)
                    .addComponent(lblRadicand))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHelpDegree)
                    .addComponent(lblDegree))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAccuracy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHelpAccuracy)
                    .addComponent(lblAccuracy))
                .addGap(18, 18, 18)
                .addComponent(btnRun)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Global variables and constants
    private RootN Root = new RootN();
    private static final String sPathHelpMain = "Help/main.html";
    private static final String sPathHelpRadicand = "Help/radicand.html";
    private static final String sPathHelpDegree = "Help/rootdegree.html";
    private static final String sPathHelpAccuracy = "Help/accuracy.html";
    //End of global variables and constants

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        this.setCursor(WAIT_CURSOR);
        txtResult.setText("");
        txtResult.repaint();
        Root.Calculate(txtRadicand.getText(), txtDegree.getText(), txtAccuracy.getText());
        txtResult.setText(Root.GetRoot());
        this.setCursor(DEFAULT_CURSOR);
    }//GEN-LAST:event_btnRunActionPerformed

    private void txtRadicandFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRadicandFocusLost
        if (txtRadicand.getText().isEmpty()) {
            return;
        }

        try {
            Integer.parseInt(txtRadicand.getText());
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "The radicand must be an integer!\r\n" + e.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
            Help.OpenFile(sPathHelpRadicand);
            txtRadicand.setText(null);
        }
    }//GEN-LAST:event_txtRadicandFocusLost

    private void jSaveXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveXMLActionPerformed
        SaveResult Save = new SaveResult();

        Save.SetRootToSave(Root.GetRoot());
        try {
            Save.SetRadicandToSave(String.valueOf(Root.GetRadicand()));
            Save.SetAccuracyToSave(String.valueOf(Root.GetAccuracy()));
            Save.SetDegreeToSave(String.valueOf(Root.GetDegree()));
            Save.SaveXML();
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Unable to save an XML file!\r\n" + e.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jSaveXMLActionPerformed

    private void txtDegreeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDegreeFocusLost
        if (txtDegree.getText().isEmpty()) {
            return;
        }

        try {
            Integer.parseInt(txtDegree.getText());
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "The degree must be an integer from 1 to 4 294 967 295\r\n" + e.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
            Help.OpenFile(sPathHelpDegree);
            txtDegree.setText(null);
        }
    }//GEN-LAST:event_txtDegreeFocusLost

    private void txtAccuracyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAccuracyFocusLost
        if (txtAccuracy.getText().isEmpty()) {
            return;
        }

        try {
            Integer.parseInt(txtAccuracy.getText());
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "The accuracy must be an integer\r\n" + e.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
            Help.OpenFile(sPathHelpAccuracy);
            txtAccuracy.setText(null);
        }
    }//GEN-LAST:event_txtAccuracyFocusLost

    private void btnHelpRadicandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpRadicandActionPerformed
        Help.OpenFile(sPathHelpRadicand);
    }//GEN-LAST:event_btnHelpRadicandActionPerformed

    private void btnHelpDegreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpDegreeActionPerformed
        Help.OpenFile(sPathHelpDegree);
    }//GEN-LAST:event_btnHelpDegreeActionPerformed

    private void btnHelpAccuracyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpAccuracyActionPerformed
        Help.OpenFile(sPathHelpAccuracy);
    }//GEN-LAST:event_btnHelpAccuracyActionPerformed

    private void jShowHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowHelpActionPerformed
        Help.OpenFile(sPathHelpMain);
    }//GEN-LAST:event_jShowHelpActionPerformed

    private void jSaveTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveTxtActionPerformed
        SaveResult Save = new SaveResult();

        Save.SetRootToSave(Root.GetRoot());
        try {
            Save.SetRadicandToSave(String.valueOf(Root.GetRadicand()));
            Save.SetAccuracyToSave(String.valueOf(Root.GetAccuracy()));
            Save.SetDegreeToSave(String.valueOf(Root.GetDegree()));
            Save.SaveTXT();
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Unable to save a TXT file!\r\n" + e.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jSaveTxtActionPerformed

    private void jRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRunActionPerformed
        btnRun.doClick();
    }//GEN-LAST:event_jRunActionPerformed

    private void jCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_jCloseActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHelpAccuracy;
    private javax.swing.JButton btnHelpDegree;
    private javax.swing.JButton btnHelpRadicand;
    private javax.swing.JButton btnRun;
    private javax.swing.JMenuItem jClose;
    private javax.swing.JMenu jHelp;
    private javax.swing.JMenuBar jMainMenu;
    private javax.swing.JMenu jProgram;
    private javax.swing.JMenuItem jRun;
    private javax.swing.JMenu jSave;
    private javax.swing.JMenuItem jSaveTxt;
    private javax.swing.JMenuItem jSaveXML;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jShowHelp;
    private javax.swing.JLabel lblAccuracy;
    private javax.swing.JLabel lblDegree;
    private javax.swing.JLabel lblRadicand;
    private javax.swing.JTextField txtAccuracy;
    private javax.swing.JTextField txtDegree;
    private javax.swing.JTextField txtRadicand;
    private javax.swing.JTextArea txtResult;
    // End of variables declaration//GEN-END:variables

}